
import triton
import triton.language as tl

from torch._inductor.runtime import triton_helpers, triton_heuristics
from torch._inductor.runtime.triton_helpers import libdevice, math as tl_math
from torch._inductor.runtime.hints import AutotuneHint, ReductionHint, TileHint, DeviceProperties
triton_helpers.set_driver_to_gpu()

# ============================================================
# Level 3: Triton Kernel (Generated by PyTorch Inductor)
# ============================================================
# 这是真实运行时由 PyTorch Inductor 生成、存放于
# /tmp/torchinductor_charlley/fr/cfraihlz75c32aaj5jxb5j32tha3hube67cgo2mfsx3j4awecujc.py
# 的完整原始 Triton Kernel。
#
# ============================================================
# 【Inductor 算子融合策略】
# ============================================================
# FX 图中有数十个离散的 aten 算子（sub, mul, add, reciprocal, div, ...）。
# Inductor 分析数据依赖，将可以在同一遍内存扫描中完成的算子融合到同一 Kernel 中。
#
# 本 Kernel 融合了以下操作（对应 FX 图 Level 2）：
#   1. LIFNode.backward() 的 ATan 替代梯度计算:
#      - sub_3 (1.0 - spike), mul_18, sub_2 (v-1), mul_20 (*(pi)),
#        pow_2, add_15, reciprocal_1, mul_21, mul_22, add_16, div_3
#   2. BatchNorm2d.backward() 的元素级部分:
#      - sub_7 (conv - mean), mul_24, mul_26 (rsqrt^2), mul_29, sub_9, sub_10, mul_30
#
# 两次内存扫描（ATen 算子层有 11+ 个算子）被合并为 1 次 GPU 全局内存往返！
#
# ============================================================
# 【各指针语义解析】
# ============================================================
# in_out_ptr0: 可读写指针，同时作为 sub_10 的输入和最终输出 (buf9 = buf8 复用显存)
# in_ptr0:     tangents_2   - 上游传入的梯度 (来自 MaxPool 反向)
# in_ptr1:     convert_element_type - LIF spike (0.0 或 1.0 的 float32 张量)
# in_ptr2:     buf4         - (conv - mean)*rsqrt*gamma + bias  (BatchNorm 输出，即 LIF 输入)
# in_ptr3:     convolution  - Conv2d 的原始输出
# in_ptr4:     getitem_1    - BatchNorm running_mean (形状 [16], 按 x1 通道索引)
# in_ptr5:     buf7 (sum_2) - BN backward 的 sum 统计量 [16]
# in_ptr6:     rsqrt        - BatchNorm 方差倒数 [16], evict_last (驻留 L2)
# in_ptr7:     buf6 (sum_3) - BN backward 的另一 sum 统计量 [16]
# in_ptr8:     primals_7    - BN 可学习参数 gamma [16], evict_last
#
# xnumel = 50176 = 4 * 16 * 28 * 28 (batch * channels * H * W)
# x3 = xindex:        全局线性索引 (0 ~ 50175)
# x1 = (x // 784) % 16: 通道维度索引 (0 ~ 15), 用于加载 per-channel 统计量
# ============================================================

@triton_heuristics.pointwise(
    size_hints={'x': 65536},
    filename=__file__,
    triton_meta={'signature': {
        'in_out_ptr0': '*fp32', 'in_ptr0': '*fp32', 'in_ptr1': '*fp32',
        'in_ptr2': '*fp32', 'in_ptr3': '*fp32', 'in_ptr4': '*fp32',
        'in_ptr5': '*fp32', 'in_ptr6': '*fp32', 'in_ptr7': '*fp32',
        'in_ptr8': '*fp32', 'xnumel': 'i32', 'XBLOCK': 'constexpr'},
        'device': DeviceProperties(type='cuda', index=0, multi_processor_count=70,
                                   cc=120, major=12, regs_per_multiprocessor=65536,
                                   max_threads_per_multi_processor=1536, warp_size=32),
        'constants': {},
        'configs': [{(0,): [['tt.divisibility', 16]], (1,): [['tt.divisibility', 16]],
                     (2,): [['tt.divisibility', 16]], (3,): [['tt.divisibility', 16]],
                     (4,): [['tt.divisibility', 16]], (5,): [['tt.divisibility', 16]],
                     (6,): [['tt.divisibility', 16]], (7,): [['tt.divisibility', 16]],
                     (8,): [['tt.divisibility', 16]], (9,): [['tt.divisibility', 16]],
                     (10,): [['tt.divisibility', 16]]}]},
    inductor_meta={
        'grid_type': 'Grid1D',
        'kernel_name': 'triton_poi_fused__native_batch_norm_legit_functional_add_div_mul_native_batch_norm_backward_pow_reciprocal_rsub_sub_3',
        'mutated_arg_names': ['in_out_ptr0'], 'optimize_mem': True,
        'num_load': 10, 'num_reduction': 0,
        'backend_hash': '2BA4C8FD5A7E74FD9CA62A3B79A28A9895DBA3FBCB8A48B100001E77B41471D7',
        'tiling_scores': {'x': 1404928}},
    min_elem_per_thread=0
)
@triton.jit
def triton_poi_fused__native_batch_norm_legit_functional_add_div_mul_native_batch_norm_backward_pow_reciprocal_rsub_sub_3(
        in_out_ptr0, in_ptr0, in_ptr1, in_ptr2, in_ptr3, in_ptr4,
        in_ptr5, in_ptr6, in_ptr7, in_ptr8, xnumel, XBLOCK: tl.constexpr):
    # ---- 线程块索引计算 ----
    # 每个 CUDA 线程块处理 XBLOCK 个元素 (由 autotune 决定, 此处为 256)
    xnumel = 50176  # = 4 * 16 * 28 * 28
    xoffset = tl.program_id(0) * XBLOCK   # 当前 CTA 的起始全局偏移
    xindex = xoffset + tl.arange(0, XBLOCK)[:]  # 形状 [XBLOCK] 的向量化索引
    xmask = xindex < xnumel               # 边界掩码（最后一个 block 可能不满）
    x3 = xindex                           # 全局线性索引
    x1 = ((xindex // 784) % 16)          # 通道索引: (全局idx / HW) % C

    # ---- 加载数据（10 次 tl.load, 全部向量化） ----
    # 注意 eviction_policy='evict_last' 用于 per-channel 统计量 (x1 索引):
    # 这是一种 L2 Cache 驱逐策略提示，告诉 GPU 将这些小张量保留在 L2 缓存中，
    # 因为它们会被同一 block 内多个线程反复读取。
    tmp0  = tl.load(in_ptr0 + (x3), xmask)                               # tangents_2
    tmp1  = tl.load(in_out_ptr0 + (x3), xmask)                           # spike (convert_element_type)
    tmp5  = tl.load(in_ptr1 + (x3), xmask)                               # div (BN output = LIF input)
    tmp14 = tl.load(in_ptr2 + (x3), xmask)                               # add_14 (chain grad)
    tmp19 = tl.load(in_ptr3 + (x3), xmask)                               # convolution (Conv output)
    tmp20 = tl.load(in_ptr4 + (x1), xmask, eviction_policy='evict_last') # BN mean [16]
    tmp22 = tl.load(in_ptr5 + (x1), xmask, eviction_policy='evict_last') # sum_2 [16]
    tmp25 = tl.load(in_ptr6 + (x1), xmask, eviction_policy='evict_last') # rsqrt [16]
    tmp30 = tl.load(in_ptr7 + (x1), xmask, eviction_policy='evict_last') # sum_3 [16]
    tmp33 = tl.load(in_ptr8 + (x1), xmask, eviction_policy='evict_last') # gamma [16]

    # ============================================================
    # 【Part A: ATan 替代梯度计算】
    # 对应 SpikingJelly surrogate.py 中 atan_backward():
    #   a = alpha / 2 = 1.0
    #   ax = pi * a * x  (但这里 x 是 LIF 的充电电位相对于阈值归一化后的值)
    # ============================================================
    tmp2  = 1.0
    tmp3  = tmp2 - tmp1        # (1 - spike): hard reset 梯度因子
                               # 对应: grad_output * (1 - spike) [aten.rsub]
    tmp4  = tmp0 * tmp3        # tangents * (1 - spike)

    tmp6  = tmp5 - tmp2        # (v_normalized - 1)  [aten.sub, v 相对 V_th=1 的偏移]
    tmp7  = 3.141592653589793  # π
    tmp8  = tmp6 * tmp7        # (v-1) * π  [第一步: ATan 的自变量预处理]
    tmp9  = tmp8 * tmp8        # ((v-1)*π)^2  [aten.pow ^2]
    tmp10 = tmp9 + tmp2        # 1 + ((v-1)*π)^2  [分母]
    tmp11 = tl.full([1], 1, tl.int32)
    tmp12 = (tmp11 / tmp10)    # 1 / (1 + ((v-1)*π)^2)  [aten.reciprocal]
    tmp13 = tmp12 * tmp2       # * 1.0  (alpha/2 = 1.0，乘以 1 无实际效果)
    tmp15 = tmp13 * tmp14      # * chain_grad  [链式法则]
    tmp16 = tmp4 + tmp15       # 汇总两条梯度路径
    tmp17 = 0.5
    tmp18 = tmp16 * tmp17      # * 0.5  (最终除以 2, 对应 alpha=2 的整体系数)
    # tmp18 = grad_atan_lif = 完整的 LIF ATan surrogate 反向梯度

    # ============================================================
    # 【Part B: BatchNorm2d 反向传播 (Elementwise 部分)】
    # 标准 BN backward 公式:
    #   dx = gamma/std * (dout - mean(dout) - x_hat * mean(dout * x_hat))
    # 这里的 mean(...) 部分已在 Reduction Kernel (Level 2 的 triton_red_..._2) 中计算完毕
    # 存入 sum_2 (tmp22) 和 sum_3 (tmp30)，这里只做 Elementwise 操作。
    # ============================================================
    tmp21 = tmp19 - tmp20      # (conv_output - BN_mean): 即 X - μ
    tmp23 = 0.00031887755102040814  # = 1 / (4 * 784) = 1 / (N * H * W), BN 归一化系数
    tmp24 = tmp22 * tmp23      # sum_2 * (1/N)
    tmp26 = tmp25 * tmp25      # rsqrt^2 = 1/var
    tmp27 = tmp24 * tmp26      # (sum_2/N) * (1/var) = E[dout] / std^2
    tmp28 = tmp21 * tmp27      # (X - μ) * E[dout] / std^2
    tmp29 = tmp18 - tmp28      # 从 LIF 梯度中减去 BN 均值修正项
    tmp31 = tmp30 * tmp23      # sum_3 * (1/N) = E[dout]
    tmp32 = tmp29 - tmp31      # 再减去 BN 的 bias 修正项
    tmp34 = tmp25 * tmp33      # rsqrt * gamma  (= gamma/std)
    tmp35 = tmp32 * tmp34      # * (gamma/std)  最终乘以 BN 的缩放因子

    # ---- 写回结果 ----
    # 将最终梯度写回 in_out_ptr0 (in-place 复用了 convert_element_type 的显存)
    tl.store(in_out_ptr0 + (x3), tmp35, xmask)
